//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AugricultureNonPointSourcePollutionEntities2 : DbContext
    {
        public AugricultureNonPointSourcePollutionEntities2()
            : base("name=AugricultureNonPointSourcePollutionEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AP_AqualCulture> AP_AqualCulture { get; set; }
        public DbSet<AP_Area> AP_Area { get; set; }
        public DbSet<AP_ArgricultureLive> AP_ArgricultureLive { get; set; }
        public DbSet<AP_LiveStockBreeding> AP_LiveStockBreeding { get; set; }
        public DbSet<AP_PlantNoPointSource> AP_PlantNoPointSource { get; set; }
        public DbSet<AP_LiveStockBreedingCoeffecient> AP_LiveStockBreedingCoeffecient { get; set; }
        public DbSet<AP_PullutionSum> AP_PullutionSum { get; set; }
    }
}
